//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSPets.DBAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animai
    {
        public int AnimalID { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DtDesaparecimento { get; set; }
        public string FotoUrl { get; set; }
        public string Whatsapp { get; set; }
        public int AnimalCategoriaID { get; set; }
        public bool excluido { get; set; }
        public int SituacaoAnimalID { get; set; }
        public int CidadeID { get; set; }
        public string FriendlyUrl { get; set; }
        public string Descricao { get; set; }
        public string Bairro { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual AnimaisCategoria AnimaisCategoria { get; set; }
        public virtual cidade cidade { get; set; }
        public virtual SituacaoAnimal SituacaoAnimal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
