//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSPets.DBAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string uf { get; set; }
        public Nullable<int> ibge { get; set; }
        public Nullable<int> pais { get; set; }
        public string ddd { get; set; }
    }
}
