//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSPets.DBAcess
{
    using System;
    
    public partial class vwAnimalCidades
    {
        public int CidadeID { get; set; }
        public string NomeCidade { get; set; }
        public Nullable<int> QtdeAnimaisCidade { get; set; }
    }
}
