//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSPets.DBAcess
{
    using System;
    
    public partial class vwAnimalList
    {
        public int AnimalID { get; set; }
        public string FotoUrl { get; set; }
        public string Whatsapp { get; set; }
        public string NomeAnimal { get; set; }
        public string Descricao { get; set; }
        public string FriendlyUrl { get; set; }
        public string DtDesaparecimento { get; set; }
        public string Bairro { get; set; }
        public string CategoriaAnimal { get; set; }
        public string SituacaoAnimal { get; set; }
        public string StatusAnimal { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string UF { get; set; }
        public Nullable<long> RowNumber { get; set; }
    }
}
